# Generated by Django 5.0.3 on 2024-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_remove_employee_age_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='access_code',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
    ]
