# Generated by Django 5.0.3 on 2024-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0004_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Production', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(default='Worker', max_length=50),
        ),
    ]
