# Generated by Django 5.0.3 on 2024-05-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='access_code',
            new_name='access_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='area',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_task',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_task',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='team_task',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
