# Generated by Django 5.0.3 on 2024-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_alter_employee_department_alter_employee_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help_question',
            name='answer',
            field=models.CharField(choices=[('Go to your profile > account > Change username > then fill the formulary, with your new username and password.', 'Go to your profile > account > Change username > then fill the formulary, with your new username and password.'), ('Go to help(this page), then send a request on bottom help formulary with the reason "Delete account". Then wait for 1 - 3 habilited days to get your account deleted.', 'Go to help(this page), then send a request on bottom help formulary with the reason "Delete account". Then wait for 1 - 3 habilited days to get your account deleted.')]),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='category',
            field=models.CharField(choices=[('Account', 'Account'), ('Account', 'Account')]),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='question',
            field=models.CharField(choices=[('How to change my username?', 'How to change my username?'), ('How to create an delete my account?', 'How to create an delete my account?')]),
        ),
    ]
