# Generated by Django 5.0.3 on 2024-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_alter_help_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help_question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='help_question',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
