# Generated by Django 5.0.3 on 2024-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_rename_access_code_team_access_key_remove_team_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
