# Generated by Django 5.0.3 on 2024-06-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_task',
            name='priority',
        ),
    ]
