# Generated by Django 5.0.3 on 2024-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_remove_team_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_task',
            name='status',
        ),
        migrations.AddField(
            model_name='team_task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
